name: Agent Safety & Alignment
description: Real-time agent safety monitoring dashboard
runtime:
  language: PYTHON
  version: "3.11"
entrypoint: streamlit run app.py --server.port 8000 --server.address 0.0.0.0
